# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

output: prefixed

vars:
  PORT_API: '8080'
  PORT_WEB: '3001'
  PORT_DUMMY_SERVER: '9999'

dotenv:
  - .env

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  # Development tasks
  dev:
    desc: Run Go server with hot reload (air)
    cmds:
      - go tool air --build.cmd="go build -o tmp/pulse-server cmd/server/main.go" --build.bin="tmp/pulse-server"

  dev:api:
    desc: Run Go server with hot reload on port 8080
    env:
      PORT: '{{.PORT_API}}'
    cmds:
      - go tool air --build.cmd="go build -o tmp/pulse-server cmd/server/main.go" --build.bin="tmp/pulse-server"

  dev:worker:
    desc: Run Go worker with hot reload (air)
    cmds:
      - go tool air --build.cmd="go build -o tmp/pulse-worker cmd/worker/main.go" --build.bin="tmp/pulse-worker"

  dev:web:
    desc: Run web frontend with pnpm dev on port 3001
    env:
      PORT: '{{.PORT_WEB}}'
    cmds:
      - pnpm dev

  dev:all:
    desc: Run both API, worker and web in parallel
    deps:
      - dev:api
      - dev:worker
      - dev:web

  # Run tasks (without hot reload)
  run:api:
    desc: Run Go server directly
    cmds:
      - go run cmd/server/main.go

  run:worker:
    desc: Run Go worker directly
    cmds:
      - go run cmd/worker/main.go

  run:dummy-server:
    desc: Run dummy HTTP server for testing
    env:
      PORT: '{{.PORT_DUMMY_SERVER}}'
    cmds:
      - go run cmd/dummy-server/main.go

  # Build tasks
  build:api:
    desc: Build server binary
    cmds:
      - mkdir -p build
      - go build -o build/server cmd/server/main.go

  build:worker:
    desc: Build worker binary
    cmds:
      - mkdir -p build
      - go build -o build/worker cmd/worker/main.go

  build:web:
    desc: Build web
    cmds:
      - pnpm build

  build:all:
    desc: Build both server and worker binaries
    deps:
      - build:api
      - build:worker
      - build:web

  # Database migration tasks
  db:migrate:
    desc: Run all pending database migrations
    cmds:
      - go run cmd/db/migrate.go up

  db:migrate:to:
    desc: 'Migrate to a specific migration ID (usage: task db:migrate:to <migration-id>)'
    cmds:
      - go run cmd/db/migrate.go up {{.CLI_ARGS}}

  db:rollback:
    desc: Rollback the last migration
    cmds:
      - go run cmd/db/migrate.go down

  db:rollback:to:
    desc: 'Rollback to a specific migration ID (usage: task db:rollback:to <migration-id>)'
    cmds:
      - go run cmd/db/migrate.go down {{.CLI_ARGS}}

  # Docker tasks
  docker:infra:up:
    desc: Start docker compose infrastructure (postgres, valkey, clickhouse)
    cmds:
      - docker compose -f docker-compose.infrastructure.yml up -d

  docker:infra:down:
    desc: Stop docker compose infrastructure
    cmds:
      - docker compose -f docker-compose.infrastructure.yml down

  docker:up:
    desc: Start full docker compose stack (includes server, worker, web, migrator)
    cmds:
      - docker compose up -d

  docker:down:
    desc: Stop full docker compose stack
    cmds:
      - docker compose down

  # Cleanup tasks
  clean:
    desc: Remove build and tmp directories
    cmds:
      - rm -rf build
      - rm -rf tmp
