openapi: 3.1.1
info:
  title: Pulse API
  description: API for Pulse monitoring system
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1
    description: Local development server
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token obtained from /auth/login or /auth/register
